### ISSUE TITLE
Default export?

### ISSUE THREAD

**Issue by davvidbaker** [nolanlawson/marky#13]
There might be a reason you are choosing not to have a default export, but would you be opposed to adding one? It's not that much of a hassle to just use `import * as marky from 'marky' `when using this module, but it took me a few minutes to realize there was no default export, and I thought others might hit this same bump in the road 🤷.

The only change would be adding this line to the bottom of index.js.
```
export default { mark, stop, getEntries, clear }
```

I'd be happy to make a PR, if it's something you are not opposed to. Thanks for the handy module btw! 👍

**Comment by nolanlawson** [comment]
I chose not to add a default export, because being explicit about the imports can result in smaller bundle sizes. Thanks for the suggestion, though! :)
