### ISSUE TITLE
Add support for Node.js Performance Timing API

### ISSUE THREAD

**Issue by ehmicky** [nolanlawson/marky#17]
Node.js `8.5.0` includes [`performance.measure()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_measure_name_startmark_endmark), [`performance.mark()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_mark_name), [`performance.clearMarks()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_clearmarks_name) and [`performanceObserverEntryList.getEntries()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performanceobserverentrylist_getentries).

Adding support would be nice. Thanks for this library!

**Comment by nolanlawson** [comment]
Node 16 now exposes a global `performance` object, so this is automatically fixed in Node 16.

See discussion in #29

**Comment by nolanlawson** [comment]
In #31 we removed the built-in Node `performance` API in v16, so this issue should be reopened. We need to figure out the perf degradation issue in Node before switching back, though.

**Comment by nolanlawson** [comment]
Currently our tests fail when using Node's built-in `performance` API. I filed a bug: https://github.com/nodejs/node/issues/42024
